### ISSUE TITLE
Add the ability to hide sticky at some page y

### ISSUE THREAD

**Issue by ptopenweb** [YJSGframework/demo-docs#1]
The sticky feature is very cool! Great work!

Is there any chance it can be improved with a new parameter (like "data-pushed-end") so we can say that the sticky will be hide at yyypx?

Example:

`<div class="yjsg-sticky" data-hide="yes" data-pushed-start="50" data-pushed-end="200"  data-offset="100" data-effect="slide" data-sticky-block=""><span class="yjtb_close"></span><div class="inside-container"><span class="yjsg-sub-heading">Did you know?</span><p>text text.</p></div></div>`

Thanks

**Comment by ptopenweb** [comment]
also a timeout for the sticky to disapper (ex: data-timeout="300") would be good too!

**Comment by danyj** [comment]
thnx for suggestion but please do not post them here. this is docs section not YJSG plugin.
